smtp:
  port: CEMEVYF_MESSAGE_SERVICE_SMTP_PORT
  host: CEMEVYF_MESSAGE_SERVICE_SMTP_HOST
  username: CEMEVYF_MESSAGE_SERVICE_SMTP_USERNAME
  password: CEMEVYF_MESSAGE_SERVICE_SMTP_PASSWORD
port: CEMEVYF_MESSAGE_SERVICE_SERVER_PORT
logLevel: CEMEVYF_MESSAGE_SERVICE_LOG_LEVEL
